services:
  database:
    image: postgres:13.5
    restart: always
    container_name: dev-test-case
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=dev-test-case-database
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    ports:
      - 3000:3000
volumes:
  postgres: